---
openapi: 3.1.0
info:
  title: "/mighty_wolf"
  version: 1.0.0
paths:
  "/vehicles":
    get:
      operationId: vehiclesIndex
      parameters:
      - in: query
        name: filter
        required: false
        schema:
          oneOf:
          - "$ref": "#/components/schemas/vehicleFilter"
          - items:
              "$ref": "#/components/schemas/vehicleFilter"
            type: array
      - in: query
        name: page
        required: false
        schema:
          "$ref": "#/components/schemas/vehiclePage"
      - in: query
        name: sort
        required: false
        schema:
          oneOf:
          - "$ref": "#/components/schemas/vehicleSort"
          - items:
              "$ref": "#/components/schemas/vehicleSort"
            type: array
      responses:
        '200':
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/vehicleIndexSuccessResponseBody"
          description: Successful response
    post:
      operationId: vehiclesCreate
      requestBody:
        content:
          application/json:
            schema:
              properties:
                vehicle:
                  oneOf:
                  - allOf:
                    - {}
                    - properties:
                        type:
                          const: car
                          type: string
                      required:
                      - type
                      type: object
                  - allOf:
                    - {}
                    - properties:
                        type:
                          const: motorcycle
                          type: string
                      required:
                      - type
                      type: object
                  - allOf:
                    - {}
                    - properties:
                        type:
                          const: truck
                          type: string
                      required:
                      - type
                      type: object
                  discriminator:
                    propertyName: type
              type: object
              required:
              - vehicle
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/vehicleCreateSuccessResponseBody"
          description: Successful response
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/errorResponseBody"
  "/vehicles/{id}":
    get:
      operationId: vehiclesShow
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/vehicleShowSuccessResponseBody"
          description: Successful response
    patch:
      operationId: vehiclesUpdate
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              properties:
                vehicle:
                  oneOf:
                  - allOf:
                    - {}
                    - properties:
                        type:
                          const: car
                          type: string
                      required:
                      - type
                      type: object
                  - allOf:
                    - {}
                    - properties:
                        type:
                          const: motorcycle
                          type: string
                      required:
                      - type
                      type: object
                  - allOf:
                    - {}
                    - properties:
                        type:
                          const: truck
                          type: string
                      required:
                      - type
                      type: object
                  discriminator:
                    propertyName: type
              type: object
              required:
              - vehicle
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/vehicleUpdateSuccessResponseBody"
          description: Successful response
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/errorResponseBody"
    delete:
      operationId: vehiclesDestroy
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        '204':
          description: No content
components:
  schemas:
    car:
      properties:
        brand:
          type: string
        color:
          type:
          - string
          - 'null'
        doors:
          type:
          - integer
          - 'null'
        id:
          type: string
        model:
          type: string
        type:
          type: string
        year:
          type:
          - integer
          - 'null'
      type: object
      required:
      - brand
      - color
      - doors
      - id
      - model
      - type
      - year
    error:
      properties:
        issues:
          items:
            "$ref": "#/components/schemas/issue"
          type: array
        layer:
          enum:
          - http
          - contract
          - domain
          type: string
      type: object
      required:
      - issues
      - layer
    errorResponseBody:
      "$ref": "#/components/schemas/error"
    filter:
      properties:
        AND:
          items:
            "$ref": "#/components/schemas/filter"
          type: array
        NOT:
          "$ref": "#/components/schemas/filter"
        OR:
          items:
            "$ref": "#/components/schemas/filter"
          type: array
        brand:
          oneOf:
          - type: string
          - "$ref": "#/components/schemas/stringFilter"
        model:
          oneOf:
          - type: string
          - "$ref": "#/components/schemas/stringFilter"
        type: {}
        year:
          oneOf:
          - type: integer
          - "$ref": "#/components/schemas/nullableIntegerFilter"
      type: object
    integerFilterBetween:
      properties:
        from:
          type: integer
        to:
          type: integer
      type: object
    issue:
      properties:
        code:
          type: string
        detail:
          type: string
        meta:
          properties: {}
          type: object
        path:
          items:
            type: string
          type: array
        pointer:
          type: string
      type: object
      required:
      - code
      - detail
      - meta
      - path
      - pointer
    motorcycle:
      properties:
        brand:
          type: string
        color:
          type:
          - string
          - 'null'
        engineCc:
          type:
          - integer
          - 'null'
        id:
          type: string
        model:
          type: string
        type:
          type: string
        year:
          type:
          - integer
          - 'null'
      type: object
      required:
      - brand
      - color
      - engineCc
      - id
      - model
      - type
      - year
    nullableIntegerFilter:
      properties:
        between:
          "$ref": "#/components/schemas/integerFilterBetween"
        eq:
          type: integer
        gt:
          type: integer
        gte:
          type: integer
        in:
          items:
            type: integer
          type: array
        lt:
          type: integer
        lte:
          type: integer
        'null':
          type: boolean
      type: object
    offsetPagination:
      properties:
        current:
          type: integer
        items:
          type: integer
        next:
          type:
          - integer
          - 'null'
        prev:
          type:
          - integer
          - 'null'
        total:
          type: integer
      type: object
      required:
      - current
      - items
      - total
    stringFilter:
      properties:
        contains:
          type: string
        endsWith:
          type: string
        eq:
          type: string
        in:
          items:
            type: string
          type: array
        startsWith:
          type: string
      type: object
    truck:
      properties:
        brand:
          type: string
        color:
          type:
          - string
          - 'null'
        id:
          type: string
        model:
          type: string
        payloadCapacity:
          type:
          - number
          - 'null'
        type:
          type: string
        year:
          type:
          - integer
          - 'null'
      type: object
      required:
      - brand
      - color
      - id
      - model
      - payloadCapacity
      - type
      - year
    vehicle:
      oneOf:
      - "$ref": "#/components/schemas/car"
      - "$ref": "#/components/schemas/motorcycle"
      - "$ref": "#/components/schemas/truck"
      discriminator:
        mapping:
          car: "#/components/schemas/car"
          motorcycle: "#/components/schemas/motorcycle"
          truck: "#/components/schemas/truck"
        propertyName: type
    vehicleCreateSuccessResponseBody:
      properties:
        meta:
          properties: {}
          type: object
        vehicle:
          "$ref": "#/components/schemas/vehicle"
      type: object
      required:
      - vehicle
    vehicleFilter:
      properties:
        AND:
          items:
            "$ref": "#/components/schemas/filter"
          type: array
        NOT:
          "$ref": "#/components/schemas/filter"
        OR:
          items:
            "$ref": "#/components/schemas/filter"
          type: array
        brand:
          oneOf:
          - type: string
          - "$ref": "#/components/schemas/stringFilter"
        model:
          oneOf:
          - type: string
          - "$ref": "#/components/schemas/stringFilter"
        type:
          "$ref": "#/components/schemas/vehicleTypeFilter"
        year:
          oneOf:
          - type: integer
          - "$ref": "#/components/schemas/nullableIntegerFilter"
      type: object
    vehicleIndexSuccessResponseBody:
      properties:
        meta:
          properties: {}
          type: object
        pagination:
          "$ref": "#/components/schemas/offsetPagination"
        vehicles:
          items:
            "$ref": "#/components/schemas/vehicle"
          type: array
      type: object
      required:
      - pagination
      - vehicles
    vehiclePage:
      properties:
        number:
          type: integer
          minimum: 1
        size:
          type: integer
          minimum: 1
          maximum: 100
      type: object
    vehicleShowSuccessResponseBody:
      properties:
        meta:
          properties: {}
          type: object
        vehicle:
          "$ref": "#/components/schemas/vehicle"
      type: object
      required:
      - vehicle
    vehicleSort:
      properties:
        year:
          enum:
          - asc
          - desc
          type: string
      type: object
    vehicleTypeFilter:
      oneOf:
      - enum:
        - car
        - motorcycle
        - truck
        type: string
      - properties:
          eq:
            enum:
            - car
            - motorcycle
            - truck
            type: string
          in:
            items:
              enum:
              - car
              - motorcycle
              - truck
              type: string
            type: array
        type: object
        required:
        - eq
        - in
    vehicleUpdateSuccessResponseBody:
      properties:
        meta:
          properties: {}
          type: object
        vehicle:
          "$ref": "#/components/schemas/vehicle"
      type: object
      required:
      - vehicle
