---
:openapi: 3.1.0
:info:
  :title: "/grumpy-panda API"
  :version: 1.0.0
:paths:
  activities/:
    get:
      :operationId: activities_index
      :tags:
      - Activities
      :parameters:
      - :in: query
        :name: include
        :required: false
        :schema:
          :$ref: "#/components/schemas/activity_include"
      - :in: query
        :name: page
        :required: false
        :schema:
          :$ref: "#/components/schemas/activity_page"
      :responses:
        :200:
          :description: Successful response
          :content:
            :application/json:
              :schema:
                :type: object
                :properties:
                  activities:
                    :type: array
                    :items:
                      :$ref: "#/components/schemas/activity"
                  meta:
                    :type: object
                    :properties: {}
                  pagination:
                    :$ref: "#/components/schemas/cursor_pagination"
    post:
      :operationId: activities_create
      :tags:
      - Activities
      :requestBody:
        :required: true
        :content:
          :application/json:
            :schema:
              :type: object
              :properties:
                activity:
                  :$ref: "#/components/schemas/activity_create_payload"
              :required:
              - activity
      :responses:
        :200:
          :description: Successful response
          :content:
            :application/json:
              :schema:
                :type: object
                :properties:
                  activity:
                    :$ref: "#/components/schemas/activity"
                  meta:
                    :type: object
                    :properties: {}
                :required:
                - activity
        :422:
          :description: Unprocessable Entity
          :content:
            :application/json:
              :schema:
                :type: object
                :properties:
                  issues:
                    :type: array
                    :items:
                      :$ref: "#/components/schemas/issue"
  activities/:id:
    get:
      :operationId: activities_show
      :tags:
      - Activities
      :responses:
        :200:
          :description: Successful response
          :content:
            :application/json:
              :schema:
                :type: object
                :properties:
                  activity:
                    :$ref: "#/components/schemas/activity"
                  meta:
                    :type: object
                    :properties: {}
                :required:
                - activity
    patch:
      :operationId: activities_update
      :tags:
      - Activities
      :requestBody:
        :required: true
        :content:
          :application/json:
            :schema:
              :type: object
              :properties:
                activity:
                  :$ref: "#/components/schemas/activity_update_payload"
      :responses:
        :200:
          :description: Successful response
          :content:
            :application/json:
              :schema:
                :type: object
                :properties:
                  activity:
                    :$ref: "#/components/schemas/activity"
                  meta:
                    :type: object
                    :properties: {}
        :422:
          :description: Unprocessable Entity
          :content:
            :application/json:
              :schema:
                :type: object
                :properties:
                  issues:
                    :type: array
                    :items:
                      :$ref: "#/components/schemas/issue"
    delete:
      :operationId: activities_destroy
      :tags:
      - Activities
      :responses:
        :204:
          :description: No content
:components:
  :schemas:
    activity:
      :type: object
      :properties:
        action:
          :type: string
        created_at:
          :type: string
        id:
          :type: string
        occurred_at:
          :type: string
    activity_create_payload:
      :type: object
      :properties:
        action:
          :type: string
        occurred_at:
          :type:
          - string
          - 'null'
      :required:
      - action
    activity_include:
      :type: object
      :properties: {}
    activity_page:
      :type: object
      :properties:
        after:
          :type: string
        before:
          :type: string
        size:
          :type: integer
          :minimum: 1
          :maximum: 100
    activity_update_payload:
      :type: object
      :properties:
        action:
          :type: string
        occurred_at:
          :type:
          - string
          - 'null'
      :required:
      - action
    cursor_pagination:
      :type: object
      :properties:
        next_cursor:
          :type:
          - string
          - 'null'
        prev_cursor:
          :type:
          - string
          - 'null'
    issue:
      :type: object
      :properties:
        code:
          :type: string
        detail:
          :type: string
        field:
          :type: string
        path:
          :type: array
          :items:
            :type: string
      :required:
      - code
      - detail
      - field
      - path
