---
:openapi: 3.1.0
:info:
  :title: "/swift-fox API"
  :version: 1.0.0
:paths:
  contacts/:
    get:
      :operationId: contacts_index
      :tags:
      - Contacts
      :parameters:
      - :in: query
        :name: filter
        :required: false
        :schema:
          :oneOf:
          - :$ref: "#/components/schemas/contact_filter"
          - :type: array
            :items:
              :$ref: "#/components/schemas/contact_filter"
      - :in: query
        :name: include
        :required: false
        :schema:
          :$ref: "#/components/schemas/contact_include"
      - :in: query
        :name: page
        :required: false
        :schema:
          :$ref: "#/components/schemas/contact_page"
      - :in: query
        :name: sort
        :required: false
        :schema:
          :oneOf:
          - :$ref: "#/components/schemas/contact_sort"
          - :type: array
            :items:
              :$ref: "#/components/schemas/contact_sort"
      :responses:
        :200:
          :description: Successful response
          :content:
            :application/json:
              :schema:
                :type: object
                :properties:
                  contacts:
                    :type: array
                    :items:
                      :$ref: "#/components/schemas/contact"
                  meta:
                    :type: object
                    :properties: {}
                  pagination:
                    :$ref: "#/components/schemas/page_pagination"
    post:
      :operationId: contacts_create
      :tags:
      - Contacts
      :requestBody:
        :required: true
        :content:
          :application/json:
            :schema:
              :type: object
              :properties:
                contact:
                  :$ref: "#/components/schemas/contact_create_payload"
              :required:
              - contact
      :responses:
        :200:
          :description: Successful response
          :content:
            :application/json:
              :schema:
                :type: object
                :properties:
                  contact:
                    :$ref: "#/components/schemas/contact"
                  meta:
                    :type: object
                    :properties: {}
                :required:
                - contact
        :422:
          :description: Unprocessable Entity
          :content:
            :application/json:
              :schema:
                :type: object
                :properties:
                  issues:
                    :type: array
                    :items:
                      :$ref: "#/components/schemas/issue"
  contacts/:id:
    get:
      :operationId: contacts_show
      :tags:
      - Contacts
      :responses:
        :200:
          :description: Successful response
          :content:
            :application/json:
              :schema:
                :type: object
                :properties:
                  contact:
                    :$ref: "#/components/schemas/contact"
                  meta:
                    :type: object
                    :properties: {}
                :required:
                - contact
    patch:
      :operationId: contacts_update
      :tags:
      - Contacts
      :requestBody:
        :required: true
        :content:
          :application/json:
            :schema:
              :type: object
              :properties:
                contact:
                  :$ref: "#/components/schemas/contact_update_payload"
      :responses:
        :200:
          :description: Successful response
          :content:
            :application/json:
              :schema:
                :type: object
                :properties:
                  contact:
                    :$ref: "#/components/schemas/contact"
                  meta:
                    :type: object
                    :properties: {}
        :422:
          :description: Unprocessable Entity
          :content:
            :application/json:
              :schema:
                :type: object
                :properties:
                  issues:
                    :type: array
                    :items:
                      :$ref: "#/components/schemas/issue"
    delete:
      :operationId: contacts_destroy
      :tags:
      - Contacts
      :responses:
        :204:
          :description: No content
:components:
  :schemas:
    contact:
      :type: object
      :properties:
        email:
          :type: string
        id:
          :type: string
        name:
          :type: string
        notes:
          :type: string
        phone:
          :type: string
    contact_create_payload:
      :type: object
      :properties:
        email:
          :type:
          - string
          - 'null'
        name:
          :type: string
        notes:
          :type: string
        phone:
          :type: string
      :required:
      - name
    contact_filter:
      :type: object
      :properties:
        _and:
          :type: array
          :items:
            :$ref: "#/components/schemas/contact_filter"
        _not:
          :$ref: "#/components/schemas/contact_filter"
        _or:
          :type: array
          :items:
            :$ref: "#/components/schemas/contact_filter"
    contact_include:
      :type: object
      :properties: {}
    contact_page:
      :type: object
      :properties:
        number:
          :type: integer
          :minimum: 1
        size:
          :type: integer
          :minimum: 1
          :maximum: 100
    contact_sort:
      :type: object
      :properties: {}
    contact_update_payload:
      :type: object
      :properties:
        email:
          :type:
          - string
          - 'null'
        name:
          :type: string
        notes:
          :type: string
        phone:
          :type: string
      :required:
      - name
    issue:
      :type: object
      :properties:
        code:
          :type: string
        detail:
          :type: string
        field:
          :type: string
        path:
          :type: array
          :items:
            :type: string
      :required:
      - code
      - detail
      - field
      - path
    page_pagination:
      :type: object
      :properties:
        current:
          :type: integer
        items:
          :type: integer
        next:
          :type:
          - integer
          - 'null'
        prev:
          :type:
          - integer
          - 'null'
        total:
          :type: integer
      :required:
      - current
      - items
      - total
