---
openapi: 3.1.0
info:
  title: "/grumpy_panda API"
  version: 1.0.0
paths:
  activities/:
    get:
      operationId: activitiesIndex
      parameters:
      - in: query
        name: page
        required: false
        schema:
          "$ref": "#/components/schemas/activityPage"
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/activityIndexSuccessResponseBody"
    post:
      operationId: activitiesCreate
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                activity:
                  "$ref": "#/components/schemas/activityCreatePayload"
              type: object
              required:
              - activity
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/activityCreateSuccessResponseBody"
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/errorResponseBody"
  activities/{id}:
    get:
      operationId: activitiesShow
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/activityShowSuccessResponseBody"
    patch:
      operationId: activitiesUpdate
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                activity:
                  "$ref": "#/components/schemas/activityUpdatePayload"
              type: object
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/activityUpdateSuccessResponseBody"
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/errorResponseBody"
    delete:
      operationId: activitiesDestroy
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '204':
          description: No content
components:
  schemas:
    activity:
      type: object
      properties:
        action:
          type: string
        createdAt:
          type: string
          format: date-time
        id:
          type: string
        occurredAt:
          type:
          - string
          - 'null'
          format: date-time
      required:
      - action
      - createdAt
      - id
      - occurredAt
    activityCreatePayload:
      type: object
      properties:
        action:
          type: string
        occurredAt:
          type:
          - string
          - 'null'
          format: date-time
      required:
      - action
    activityCreateSuccessResponseBody:
      type: object
      properties:
        activity:
          "$ref": "#/components/schemas/activity"
        meta:
          type: object
          properties: {}
      required:
      - activity
    activityIndexSuccessResponseBody:
      type: object
      properties:
        activities:
          type: array
          items:
            "$ref": "#/components/schemas/activity"
        meta:
          type: object
          properties: {}
        pagination:
          "$ref": "#/components/schemas/cursorPagination"
      required:
      - activities
      - pagination
    activityPage:
      type: object
      properties:
        after:
          type: string
        before:
          type: string
        size:
          type: integer
          minimum: 1
          maximum: 100
    activityShowSuccessResponseBody:
      type: object
      properties:
        activity:
          "$ref": "#/components/schemas/activity"
        meta:
          type: object
          properties: {}
      required:
      - activity
    activityUpdatePayload:
      type: object
      properties:
        action:
          type: string
        occurredAt:
          type:
          - string
          - 'null'
          format: date-time
      required:
      - action
    activityUpdateSuccessResponseBody:
      type: object
      properties:
        activity:
          "$ref": "#/components/schemas/activity"
        meta:
          type: object
          properties: {}
      required:
      - activity
    cursorPagination:
      type: object
      properties:
        next:
          type:
          - string
          - 'null'
        prev:
          type:
          - string
          - 'null'
    errorResponseBody:
      type: object
      properties:
        issues:
          type: array
          items:
            "$ref": "#/components/schemas/issue"
        layer:
          enum:
          - http
          - contract
          - domain
          type: string
      required:
      - issues
      - layer
    issue:
      type: object
      properties:
        code:
          type: string
        detail:
          type: string
        meta:
          type: object
          properties: {}
        path:
          type: array
          items:
            type: string
        pointer:
          type: string
      required:
      - code
      - detail
      - meta
      - path
      - pointer
