---
openapi: 3.1.0
info:
  title: "/grumpy_panda"
  version: 1.0.0
paths:
  "/activities":
    get:
      operationId: activities_index
      parameters:
      - in: query
        name: page
        required: false
        schema:
          "$ref": "#/components/schemas/activity_page"
      responses:
        '200':
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/activity_index_success_response_body"
          description: Successful response
    post:
      operationId: activities_create
      requestBody:
        content:
          application/json:
            schema:
              properties:
                activity:
                  "$ref": "#/components/schemas/activity_create_payload"
              type: object
              required:
              - activity
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/activity_create_success_response_body"
          description: Successful response
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/error_response_body"
  "/activities/{id}":
    get:
      operationId: activities_show
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/activity_show_success_response_body"
          description: Successful response
    patch:
      operationId: activities_update
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              properties:
                activity:
                  "$ref": "#/components/schemas/activity_update_payload"
              type: object
              required:
              - activity
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/activity_update_success_response_body"
          description: Successful response
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/error_response_body"
    delete:
      operationId: activities_destroy
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        '204':
          description: No content
components:
  schemas:
    activity:
      properties:
        action:
          type: string
        created_at:
          type: string
          format: date-time
        id:
          type: string
        occurred_at:
          type:
          - string
          - 'null'
          format: date-time
      type: object
      required:
      - action
      - created_at
      - id
      - occurred_at
    activity_create_payload:
      properties:
        action:
          type: string
        occurred_at:
          type:
          - string
          - 'null'
          format: date-time
      type: object
      required:
      - action
    activity_create_success_response_body:
      properties:
        activity:
          "$ref": "#/components/schemas/activity"
        meta:
          properties: {}
          type: object
      type: object
      required:
      - activity
    activity_index_success_response_body:
      properties:
        activities:
          items:
            "$ref": "#/components/schemas/activity"
          type: array
        meta:
          properties: {}
          type: object
        pagination:
          "$ref": "#/components/schemas/cursor_pagination"
      type: object
      required:
      - activities
      - pagination
    activity_page:
      properties:
        after:
          type: string
        before:
          type: string
        size:
          type: integer
          minimum: 1
          maximum: 100
      type: object
    activity_show_success_response_body:
      properties:
        activity:
          "$ref": "#/components/schemas/activity"
        meta:
          properties: {}
          type: object
      type: object
      required:
      - activity
    activity_update_payload:
      properties:
        action:
          type: string
        occurred_at:
          type:
          - string
          - 'null'
          format: date-time
      type: object
    activity_update_success_response_body:
      properties:
        activity:
          "$ref": "#/components/schemas/activity"
        meta:
          properties: {}
          type: object
      type: object
      required:
      - activity
    cursor_pagination:
      properties:
        next:
          type:
          - string
          - 'null'
        prev:
          type:
          - string
          - 'null'
      type: object
    error_response_body:
      properties:
        issues:
          items:
            "$ref": "#/components/schemas/issue"
          type: array
        layer:
          enum:
          - http
          - contract
          - domain
          type: string
      type: object
      required:
      - issues
      - layer
    issue:
      properties:
        code:
          type: string
        detail:
          type: string
        meta:
          properties: {}
          type: object
        path:
          items:
            type: string
          type: array
        pointer:
          type: string
      type: object
      required:
      - code
      - detail
      - meta
      - path
      - pointer
