---
openapi: 3.1.0
info:
  title: "/funny_snake"
  version: 1.0.0
paths:
  "/invoices":
    get:
      operationId: invoices_index
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  invoices:
                    items:
                      "$ref": "#/components/schemas/invoice"
                    type: array
                type: object
                required:
                - invoices
          description: Successful response
    post:
      operationId: invoices_create
      requestBody:
        content:
          application/json:
            schema:
              properties:
                invoice:
                  "$ref": "#/components/schemas/invoice_payload"
              type: object
              required:
              - invoice
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  invoice:
                    "$ref": "#/components/schemas/invoice"
                type: object
                required:
                - invoice
          description: Successful response
  "/invoices/{id}":
    get:
      operationId: invoices_show
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  invoice:
                    "$ref": "#/components/schemas/invoice"
                type: object
                required:
                - invoice
          description: Successful response
    patch:
      operationId: invoices_update
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              properties:
                invoice:
                  "$ref": "#/components/schemas/invoice_payload"
              type: object
              required:
              - invoice
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  invoice:
                    "$ref": "#/components/schemas/invoice"
                type: object
                required:
                - invoice
          description: Successful response
    delete:
      operationId: invoices_destroy
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        '204':
          description: No content
components:
  schemas:
    invoice:
      properties:
        created_at:
          type: string
          format: date-time
        id:
          type: string
          format: uuid
        issued_on:
          type: string
          format: date
        notes:
          type: string
        number:
          type: string
        status:
          type: string
        updated_at:
          type: string
          format: date-time
      type: object
      required:
      - created_at
      - id
      - issued_on
      - notes
      - number
      - status
      - updated_at
    invoice_payload:
      properties:
        issued_on:
          type: string
          format: date
        notes:
          type: string
        number:
          type: string
        status:
          type: string
      type: object
      required:
      - issued_on
      - notes
      - number
      - status
