---
openapi: 3.1.0
info:
  title: "/bright_parrot"
  version: 1.0.0
paths:
  "/notifications":
    get:
      operationId: notificationsIndex
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  preference:
                    oneOf:
                    - allOf:
                      - properties:
                          address:
                            type: string
                          digest:
                            type: boolean
                        type: object
                        required:
                        - address
                        - digest
                      - properties:
                          channel:
                            const: email
                            type: string
                        required:
                        - channel
                        type: object
                    - allOf:
                      - properties:
                          phoneNumber:
                            type: string
                        type: object
                        required:
                        - phoneNumber
                      - properties:
                          channel:
                            const: sms
                            type: string
                        required:
                        - channel
                        type: object
                    - allOf:
                      - properties:
                          deviceToken:
                            type: string
                          silent:
                            type: boolean
                        type: object
                        required:
                        - deviceToken
                        - silent
                      - properties:
                          channel:
                            const: push
                            type: string
                        required:
                        - channel
                        type: object
                    discriminator:
                      propertyName: channel
                type: object
                required:
                - preference
          description: Successful response
    post:
      operationId: notificationsCreate
      requestBody:
        content:
          application/json:
            schema:
              properties:
                preference:
                  oneOf:
                  - allOf:
                    - properties:
                        address:
                          type: string
                        digest:
                          type: boolean
                      type: object
                      required:
                      - address
                      - digest
                    - properties:
                        channel:
                          const: email
                          type: string
                      required:
                      - channel
                      type: object
                  - allOf:
                    - properties:
                        phoneNumber:
                          type: string
                      type: object
                      required:
                      - phoneNumber
                    - properties:
                        channel:
                          const: sms
                          type: string
                      required:
                      - channel
                      type: object
                  - allOf:
                    - properties:
                        deviceToken:
                          type: string
                        silent:
                          type: boolean
                      type: object
                      required:
                      - deviceToken
                      - silent
                    - properties:
                        channel:
                          const: push
                          type: string
                      required:
                      - channel
                      type: object
                  discriminator:
                    propertyName: channel
              type: object
              required:
              - preference
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  preference:
                    oneOf:
                    - allOf:
                      - properties:
                          address:
                            type: string
                          digest:
                            type: boolean
                        type: object
                        required:
                        - address
                        - digest
                      - properties:
                          channel:
                            const: email
                            type: string
                        required:
                        - channel
                        type: object
                    - allOf:
                      - properties:
                          phoneNumber:
                            type: string
                        type: object
                        required:
                        - phoneNumber
                      - properties:
                          channel:
                            const: sms
                            type: string
                        required:
                        - channel
                        type: object
                    - allOf:
                      - properties:
                          deviceToken:
                            type: string
                          silent:
                            type: boolean
                        type: object
                        required:
                        - deviceToken
                        - silent
                      - properties:
                          channel:
                            const: push
                            type: string
                        required:
                        - channel
                        type: object
                    discriminator:
                      propertyName: channel
                type: object
                required:
                - preference
          description: Successful response
components:
  schemas: {}
