---
openapi: 3.1.0
info:
  title: "/curious_cat"
  version: 1.0.0
paths:
  "/profiles":
    get:
      operationId: profiles_index
      parameters:
      - in: query
        name: page
        required: false
        schema:
          "$ref": "#/components/schemas/profile_page"
      responses:
        '200':
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/profile_index_success_response_body"
          description: Successful response
    post:
      operationId: profiles_create
      requestBody:
        content:
          application/json:
            schema:
              properties:
                profile:
                  "$ref": "#/components/schemas/profile_create_payload"
              type: object
              required:
              - profile
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/profile_create_success_response_body"
          description: Successful response
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/error_response_body"
  "/profiles/{id}":
    get:
      operationId: profiles_show
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/profile_show_success_response_body"
          description: Successful response
    patch:
      operationId: profiles_update
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              properties:
                profile:
                  "$ref": "#/components/schemas/profile_update_payload"
              type: object
              required:
              - profile
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/profile_update_success_response_body"
          description: Successful response
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/error_response_body"
    delete:
      operationId: profiles_destroy
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        '204':
          description: No content
components:
  schemas:
    error_response_body:
      properties:
        issues:
          items:
            "$ref": "#/components/schemas/issue"
          type: array
        layer:
          enum:
          - http
          - contract
          - domain
          type: string
      type: object
      required:
      - issues
      - layer
    issue:
      properties:
        code:
          type: string
        detail:
          type: string
        meta:
          properties: {}
          type: object
        path:
          items:
            type: string
          type: array
        pointer:
          type: string
      type: object
      required:
      - code
      - detail
      - meta
      - path
      - pointer
    offset_pagination:
      properties:
        current:
          type: integer
        items:
          type: integer
        next:
          type:
          - integer
          - 'null'
        prev:
          type:
          - integer
          - 'null'
        total:
          type: integer
      type: object
      required:
      - current
      - items
      - total
    profile:
      properties:
        addresses:
          items:
            properties:
              city:
                type: string
              primary:
                type: boolean
              street:
                type: string
              zip:
                type: string
            type: object
            required:
            - city
            - primary
            - street
            - zip
          type: array
        created_at:
          type: string
          format: date-time
        email:
          type: string
          format: email
        id:
          type: string
        metadata:
          type: string
        name:
          type: string
        preferences:
          properties:
            notifications:
              properties:
                email:
                  type: boolean
                push:
                  type: boolean
              type: object
              required:
              - email
              - push
            ui:
              properties:
                sidebar_collapsed:
                  type: boolean
                theme:
                  type: string
              type: object
              required:
              - sidebar_collapsed
              - theme
          type: object
          required:
          - notifications
          - ui
        settings:
          properties:
            language:
              type: string
            notifications:
              type: boolean
            theme:
              type: string
          type: object
          required:
          - language
          - notifications
          - theme
        tags:
          items:
            type: string
          type: array
        updated_at:
          type: string
          format: date-time
      type: object
      required:
      - addresses
      - created_at
      - email
      - id
      - metadata
      - name
      - preferences
      - settings
      - tags
      - updated_at
    profile_create_payload:
      properties:
        addresses:
          items:
            properties:
              city:
                type: string
              primary:
                type: boolean
              street:
                type: string
              zip:
                type: string
            type: object
            required:
            - city
            - primary
            - street
            - zip
          type: array
        email:
          type: string
          format: email
        metadata:
          type: string
        name:
          type: string
        preferences:
          properties:
            notifications:
              properties:
                email:
                  type: boolean
                push:
                  type: boolean
              type: object
              required:
              - email
              - push
            ui:
              properties:
                sidebar_collapsed:
                  type: boolean
                theme:
                  type: string
              type: object
              required:
              - sidebar_collapsed
              - theme
          type: object
          required:
          - notifications
          - ui
        settings:
          properties:
            language:
              type: string
            notifications:
              type: boolean
            theme:
              type: string
          type: object
          required:
          - language
          - notifications
          - theme
        tags:
          items:
            type: string
          type: array
      type: object
      required:
      - addresses
      - email
      - metadata
      - name
      - preferences
      - settings
      - tags
    profile_create_success_response_body:
      properties:
        meta:
          properties: {}
          type: object
        profile:
          "$ref": "#/components/schemas/profile"
      type: object
      required:
      - profile
    profile_index_success_response_body:
      properties:
        meta:
          properties: {}
          type: object
        pagination:
          "$ref": "#/components/schemas/offset_pagination"
        profiles:
          items:
            "$ref": "#/components/schemas/profile"
          type: array
      type: object
      required:
      - pagination
      - profiles
    profile_page:
      properties:
        number:
          type: integer
          minimum: 1
        size:
          type: integer
          minimum: 1
          maximum: 100
      type: object
    profile_show_success_response_body:
      properties:
        meta:
          properties: {}
          type: object
        profile:
          "$ref": "#/components/schemas/profile"
      type: object
      required:
      - profile
    profile_update_payload:
      properties:
        addresses:
          items:
            properties:
              city:
                type: string
              primary:
                type: boolean
              street:
                type: string
              zip:
                type: string
            type: object
            required:
            - city
            - primary
            - street
            - zip
          type: array
        email:
          type: string
          format: email
        metadata:
          type: string
        name:
          type: string
        preferences:
          properties:
            notifications:
              properties:
                email:
                  type: boolean
                push:
                  type: boolean
              type: object
              required:
              - email
              - push
            ui:
              properties:
                sidebar_collapsed:
                  type: boolean
                theme:
                  type: string
              type: object
              required:
              - sidebar_collapsed
              - theme
          type: object
          required:
          - notifications
          - ui
        settings:
          properties:
            language:
              type: string
            notifications:
              type: boolean
            theme:
              type: string
          type: object
          required:
          - language
          - notifications
          - theme
        tags:
          items:
            type: string
          type: array
      type: object
    profile_update_success_response_body:
      properties:
        meta:
          properties: {}
          type: object
        profile:
          "$ref": "#/components/schemas/profile"
      type: object
      required:
      - profile
