---
openapi: 3.1.0
info:
  title: "/gentle_owl"
  version: 1.0.0
paths:
  "/comments":
    get:
      operationId: commentsIndex
      parameters:
      - in: query
        name: include
        required: false
        schema:
          "$ref": "#/components/schemas/commentInclude"
      - in: query
        name: page
        required: false
        schema:
          "$ref": "#/components/schemas/commentPage"
      - in: query
        name: sort
        required: false
        schema:
          oneOf:
          - "$ref": "#/components/schemas/commentSort"
          - items:
              "$ref": "#/components/schemas/commentSort"
            type: array
      responses:
        '200':
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/commentIndexSuccessResponseBody"
          description: Successful response
    post:
      operationId: commentsCreate
      parameters:
      - in: query
        name: include
        required: false
        schema:
          "$ref": "#/components/schemas/commentInclude"
      requestBody:
        content:
          application/json:
            schema:
              properties:
                comment:
                  "$ref": "#/components/schemas/commentCreatePayload"
              type: object
              required:
              - comment
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/commentCreateSuccessResponseBody"
          description: Successful response
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/errorResponseBody"
  "/comments/{id}":
    get:
      operationId: commentsShow
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      - in: query
        name: include
        required: false
        schema:
          "$ref": "#/components/schemas/commentInclude"
      responses:
        '200':
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/commentShowSuccessResponseBody"
          description: Successful response
    patch:
      operationId: commentsUpdate
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      - in: query
        name: include
        required: false
        schema:
          "$ref": "#/components/schemas/commentInclude"
      requestBody:
        content:
          application/json:
            schema:
              properties:
                comment:
                  "$ref": "#/components/schemas/commentUpdatePayload"
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/commentUpdateSuccessResponseBody"
          description: Successful response
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/errorResponseBody"
    delete:
      operationId: commentsDestroy
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      - in: query
        name: include
        required: false
        schema:
          "$ref": "#/components/schemas/commentInclude"
      responses:
        '204':
          description: No content
components:
  schemas:
    comment:
      properties:
        authorName:
          type:
          - string
          - 'null'
        body:
          type: string
        commentable:
          "$ref": "#/components/schemas/commentCommentable"
        createdAt:
          type: string
          format: date-time
        id:
          type: string
      type: object
      required:
      - authorName
      - body
      - createdAt
      - id
    commentCommentable:
      oneOf:
      - "$ref": "#/components/schemas/post"
      - "$ref": "#/components/schemas/video"
      - "$ref": "#/components/schemas/image"
      discriminator:
        mapping:
          post: "#/components/schemas/post"
          video: "#/components/schemas/video"
          image: "#/components/schemas/image"
        propertyName: commentableType
    commentCreatePayload:
      properties:
        authorName:
          type:
          - string
          - 'null'
        body:
          type: string
      type: object
      required:
      - body
    commentCreateSuccessResponseBody:
      properties:
        comment:
          "$ref": "#/components/schemas/comment"
        meta:
          properties: {}
          type: object
      type: object
      required:
      - comment
    commentInclude:
      properties:
        commentable:
          type: boolean
      type: object
    commentIndexSuccessResponseBody:
      properties:
        comments:
          items:
            "$ref": "#/components/schemas/comment"
          type: array
        meta:
          properties: {}
          type: object
        pagination:
          "$ref": "#/components/schemas/offsetPagination"
      type: object
      required:
      - comments
      - pagination
    commentPage:
      properties:
        number:
          type: integer
          minimum: 1
        size:
          type: integer
          minimum: 1
          maximum: 100
      type: object
    commentShowSuccessResponseBody:
      properties:
        comment:
          "$ref": "#/components/schemas/comment"
        meta:
          properties: {}
          type: object
      type: object
      required:
      - comment
    commentSort:
      properties:
        createdAt:
          enum:
          - asc
          - desc
          type: string
      type: object
    commentUpdatePayload:
      properties:
        authorName:
          type:
          - string
          - 'null'
        body:
          type: string
      type: object
      required:
      - body
    commentUpdateSuccessResponseBody:
      properties:
        comment:
          "$ref": "#/components/schemas/comment"
        meta:
          properties: {}
          type: object
      type: object
      required:
      - comment
    errorResponseBody:
      properties:
        issues:
          items:
            "$ref": "#/components/schemas/issue"
          type: array
        layer:
          enum:
          - http
          - contract
          - domain
          type: string
      type: object
      required:
      - issues
      - layer
    image:
      properties:
        comments:
          items:
            properties: {}
            type: object
          type: array
        createdAt:
          type: string
          format: date-time
        height:
          type:
          - integer
          - 'null'
        id:
          type: string
        title:
          type: string
        url:
          type: string
        width:
          type:
          - integer
          - 'null'
      type: object
      required:
      - createdAt
      - height
      - id
      - title
      - url
      - width
    imageFilter:
      properties:
        _and:
          items:
            "$ref": "#/components/schemas/imageFilter"
          type: array
        _not:
          "$ref": "#/components/schemas/imageFilter"
        _or:
          items:
            "$ref": "#/components/schemas/imageFilter"
          type: array
        title:
          oneOf:
          - type: string
          - {}
      type: object
    imageNestedCreatePayload:
      properties:
        _type:
          const: create
          type: string
        height:
          type:
          - integer
          - 'null'
        title:
          type: string
        url:
          type: string
        width:
          type:
          - integer
          - 'null'
      type: object
      required:
      - _type
      - title
      - url
    imageNestedPayload:
      oneOf:
      - "$ref": "#/components/schemas/imageNestedCreatePayload"
      - "$ref": "#/components/schemas/imageNestedUpdatePayload"
      discriminator:
        mapping:
          create: "#/components/schemas/imageNestedCreatePayload"
          update: "#/components/schemas/imageNestedUpdatePayload"
        propertyName: _type
    imageNestedUpdatePayload:
      properties:
        _type:
          const: update
          type: string
        height:
          type:
          - integer
          - 'null'
        title:
          type: string
        url:
          type: string
        width:
          type:
          - integer
          - 'null'
      type: object
      required:
      - _type
      - title
      - url
    imageSort:
      properties:
        createdAt:
          enum:
          - asc
          - desc
          type: string
      type: object
    issue:
      properties:
        code:
          type: string
        detail:
          type: string
        meta:
          properties: {}
          type: object
        path:
          items:
            type: string
          type: array
        pointer:
          type: string
      type: object
      required:
      - code
      - detail
      - meta
      - path
      - pointer
    offsetPagination:
      properties:
        current:
          type: integer
        items:
          type: integer
        next:
          type:
          - integer
          - 'null'
        prev:
          type:
          - integer
          - 'null'
        total:
          type: integer
      type: object
      required:
      - current
      - items
      - total
    post:
      properties:
        body:
          type:
          - string
          - 'null'
        comments:
          items:
            properties: {}
            type: object
          type: array
        createdAt:
          type: string
          format: date-time
        id:
          type: string
        title:
          type: string
      type: object
      required:
      - body
      - createdAt
      - id
      - title
    postFilter:
      properties:
        _and:
          items:
            "$ref": "#/components/schemas/postFilter"
          type: array
        _not:
          "$ref": "#/components/schemas/postFilter"
        _or:
          items:
            "$ref": "#/components/schemas/postFilter"
          type: array
        title:
          oneOf:
          - type: string
          - {}
      type: object
    postNestedCreatePayload:
      properties:
        _type:
          const: create
          type: string
        body:
          type:
          - string
          - 'null'
        title:
          type: string
      type: object
      required:
      - _type
      - title
    postNestedPayload:
      oneOf:
      - "$ref": "#/components/schemas/postNestedCreatePayload"
      - "$ref": "#/components/schemas/postNestedUpdatePayload"
      discriminator:
        mapping:
          create: "#/components/schemas/postNestedCreatePayload"
          update: "#/components/schemas/postNestedUpdatePayload"
        propertyName: _type
    postNestedUpdatePayload:
      properties:
        _type:
          const: update
          type: string
        body:
          type:
          - string
          - 'null'
        title:
          type: string
      type: object
      required:
      - _type
      - title
    postSort:
      properties:
        createdAt:
          enum:
          - asc
          - desc
          type: string
      type: object
    video:
      properties:
        comments:
          items:
            properties: {}
            type: object
          type: array
        createdAt:
          type: string
          format: date-time
        duration:
          type:
          - integer
          - 'null'
        id:
          type: string
        title:
          type: string
        url:
          type: string
      type: object
      required:
      - createdAt
      - duration
      - id
      - title
      - url
    videoFilter:
      properties:
        _and:
          items:
            "$ref": "#/components/schemas/videoFilter"
          type: array
        _not:
          "$ref": "#/components/schemas/videoFilter"
        _or:
          items:
            "$ref": "#/components/schemas/videoFilter"
          type: array
        title:
          oneOf:
          - type: string
          - {}
      type: object
    videoNestedCreatePayload:
      properties:
        _type:
          const: create
          type: string
        duration:
          type:
          - integer
          - 'null'
        title:
          type: string
        url:
          type: string
      type: object
      required:
      - _type
      - title
      - url
    videoNestedPayload:
      oneOf:
      - "$ref": "#/components/schemas/videoNestedCreatePayload"
      - "$ref": "#/components/schemas/videoNestedUpdatePayload"
      discriminator:
        mapping:
          create: "#/components/schemas/videoNestedCreatePayload"
          update: "#/components/schemas/videoNestedUpdatePayload"
        propertyName: _type
    videoNestedUpdatePayload:
      properties:
        _type:
          const: update
          type: string
        duration:
          type:
          - integer
          - 'null'
        title:
          type: string
        url:
          type: string
      type: object
      required:
      - _type
      - title
      - url
    videoSort:
      properties:
        createdAt:
          enum:
          - asc
          - desc
          type: string
      type: object
