---
openapi: 3.1.0
info:
  title: "/gentle_owl"
  version: 1.0.0
paths:
  "/comments":
    get:
      operationId: comments_index
      parameters:
      - in: query
        name: include
        required: false
        schema:
          "$ref": "#/components/schemas/comment_include"
      - in: query
        name: page
        required: false
        schema:
          "$ref": "#/components/schemas/comment_page"
      - in: query
        name: sort
        required: false
        schema:
          oneOf:
          - "$ref": "#/components/schemas/comment_sort"
          - items:
              "$ref": "#/components/schemas/comment_sort"
            type: array
      responses:
        '200':
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/comment_index_success_response_body"
          description: Successful response
    post:
      operationId: comments_create
      parameters:
      - in: query
        name: include
        required: false
        schema:
          "$ref": "#/components/schemas/comment_include"
      requestBody:
        content:
          application/json:
            schema:
              properties:
                comment:
                  "$ref": "#/components/schemas/comment_create_payload"
              type: object
              required:
              - comment
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/comment_create_success_response_body"
          description: Successful response
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/error_response_body"
  "/comments/{id}":
    get:
      operationId: comments_show
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      - in: query
        name: include
        required: false
        schema:
          "$ref": "#/components/schemas/comment_include"
      responses:
        '200':
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/comment_show_success_response_body"
          description: Successful response
    patch:
      operationId: comments_update
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      - in: query
        name: include
        required: false
        schema:
          "$ref": "#/components/schemas/comment_include"
      requestBody:
        content:
          application/json:
            schema:
              properties:
                comment:
                  "$ref": "#/components/schemas/comment_update_payload"
              type: object
              required:
              - comment
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/comment_update_success_response_body"
          description: Successful response
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/error_response_body"
    delete:
      operationId: comments_destroy
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      - in: query
        name: include
        required: false
        schema:
          "$ref": "#/components/schemas/comment_include"
      responses:
        '204':
          description: No content
components:
  schemas:
    comment:
      properties:
        author_name:
          type:
          - string
          - 'null'
        body:
          type: string
        commentable:
          "$ref": "#/components/schemas/comment_commentable"
        created_at:
          type: string
          format: date-time
        id:
          type: string
      type: object
      required:
      - author_name
      - body
      - created_at
      - id
    comment_commentable:
      oneOf:
      - allOf:
        - "$ref": "#/components/schemas/post"
        - properties:
            commentable_type:
              const: post
              type: string
          required:
          - commentable_type
          type: object
      - allOf:
        - "$ref": "#/components/schemas/video"
        - properties:
            commentable_type:
              const: video
              type: string
          required:
          - commentable_type
          type: object
      - allOf:
        - "$ref": "#/components/schemas/image"
        - properties:
            commentable_type:
              const: image
              type: string
          required:
          - commentable_type
          type: object
      discriminator:
        mapping:
          post: "#/components/schemas/post"
          video: "#/components/schemas/video"
          image: "#/components/schemas/image"
        propertyName: commentable_type
    comment_create_payload:
      properties:
        author_name:
          type:
          - string
          - 'null'
        body:
          type: string
      type: object
      required:
      - body
    comment_create_success_response_body:
      properties:
        comment:
          "$ref": "#/components/schemas/comment"
        meta:
          properties: {}
          type: object
      type: object
      required:
      - comment
    comment_include:
      properties:
        commentable:
          type: boolean
      type: object
    comment_index_success_response_body:
      properties:
        comments:
          items:
            "$ref": "#/components/schemas/comment"
          type: array
        meta:
          properties: {}
          type: object
        pagination:
          "$ref": "#/components/schemas/offset_pagination"
      type: object
      required:
      - comments
      - pagination
    comment_page:
      properties:
        number:
          type: integer
          minimum: 1
        size:
          type: integer
          minimum: 1
          maximum: 100
      type: object
    comment_show_success_response_body:
      properties:
        comment:
          "$ref": "#/components/schemas/comment"
        meta:
          properties: {}
          type: object
      type: object
      required:
      - comment
    comment_sort:
      properties:
        created_at:
          enum:
          - asc
          - desc
          type: string
      type: object
    comment_update_payload:
      properties:
        author_name:
          type:
          - string
          - 'null'
        body:
          type: string
      type: object
    comment_update_success_response_body:
      properties:
        comment:
          "$ref": "#/components/schemas/comment"
        meta:
          properties: {}
          type: object
      type: object
      required:
      - comment
    error_response_body:
      properties:
        issues:
          items:
            "$ref": "#/components/schemas/issue"
          type: array
        layer:
          enum:
          - http
          - contract
          - domain
          type: string
      type: object
      required:
      - issues
      - layer
    image:
      properties:
        comments:
          items:
            properties: {}
            type: object
          type: array
        created_at:
          type: string
          format: date-time
        height:
          type:
          - integer
          - 'null'
        id:
          type: string
        title:
          type: string
        url:
          type: string
        width:
          type:
          - integer
          - 'null'
      type: object
      required:
      - created_at
      - height
      - id
      - title
      - url
      - width
    issue:
      properties:
        code:
          type: string
        detail:
          type: string
        meta:
          properties: {}
          type: object
        path:
          items:
            type: string
          type: array
        pointer:
          type: string
      type: object
      required:
      - code
      - detail
      - meta
      - path
      - pointer
    offset_pagination:
      properties:
        current:
          type: integer
        items:
          type: integer
        next:
          type:
          - integer
          - 'null'
        prev:
          type:
          - integer
          - 'null'
        total:
          type: integer
      type: object
      required:
      - current
      - items
      - total
    post:
      properties:
        body:
          type:
          - string
          - 'null'
        comments:
          items:
            properties: {}
            type: object
          type: array
        created_at:
          type: string
          format: date-time
        id:
          type: string
        title:
          type: string
      type: object
      required:
      - body
      - created_at
      - id
      - title
    video:
      properties:
        comments:
          items:
            properties: {}
            type: object
          type: array
        created_at:
          type: string
          format: date-time
        duration:
          type:
          - integer
          - 'null'
        id:
          type: string
        title:
          type: string
        url:
          type: string
      type: object
      required:
      - created_at
      - duration
      - id
      - title
      - url
