---
:openapi: 3.1.0
:info:
  :title: "/swift-fox API"
  :version: 1.0.0
:paths:
  posts/:
    get:
      :operationId: postsIndex
      :summary: List posts
      :tags:
      - Posts
      :parameters:
      - :in: query
        :name: filter
        :required: false
        :schema:
          :oneOf:
          - :$ref: "#/components/schemas/postFilter"
          - :type: array
            :items:
              :$ref: "#/components/schemas/postFilter"
      - :in: query
        :name: include
        :required: false
        :schema:
          :$ref: "#/components/schemas/postInclude"
      - :in: query
        :name: page
        :required: false
        :schema:
          :$ref: "#/components/schemas/postPage"
      - :in: query
        :name: sort
        :required: false
        :schema:
          :oneOf:
          - :$ref: "#/components/schemas/postSort"
          - :type: array
            :items:
              :$ref: "#/components/schemas/postSort"
      :responses:
        :200:
          :description: Successful response
          :content:
            :application/json:
              :schema:
                :type: object
                :properties:
                  meta:
                    :type: object
                    :properties: {}
                  pagination:
                    :$ref: "#/components/schemas/pagePagination"
                  posts:
                    :type: array
                    :items:
                      :$ref: "#/components/schemas/post"
    post:
      :operationId: postsCreate
      :summary: Create post
      :tags:
      - Posts
      :requestBody:
        :required: true
        :content:
          :application/json:
            :schema:
              :type: object
              :properties:
                post:
                  :$ref: "#/components/schemas/postCreatePayload"
              :required:
              - post
      :responses:
        :200:
          :description: Successful response
          :content:
            :application/json:
              :schema:
                :type: object
                :properties:
                  meta:
                    :type: object
                    :properties: {}
                  post:
                    :$ref: "#/components/schemas/post"
                :required:
                - post
        :422:
          :description: Unprocessable Entity
          :content:
            :application/json:
              :schema:
                :type: object
                :properties:
                  issues:
                    :type: array
                    :items:
                      :$ref: "#/components/schemas/issue"
                :required:
                - issues
  posts/:id:
    get:
      :operationId: postsShow
      :summary: Get post
      :tags:
      - Posts
      :responses:
        :200:
          :description: Successful response
          :content:
            :application/json:
              :schema:
                :type: object
                :properties:
                  meta:
                    :type: object
                    :properties: {}
                  post:
                    :$ref: "#/components/schemas/post"
                :required:
                - post
    patch:
      :operationId: postsUpdate
      :summary: Update post
      :tags:
      - Posts
      :requestBody:
        :required: true
        :content:
          :application/json:
            :schema:
              :type: object
              :properties:
                post:
                  :$ref: "#/components/schemas/postUpdatePayload"
      :responses:
        :200:
          :description: Successful response
          :content:
            :application/json:
              :schema:
                :type: object
                :properties:
                  meta:
                    :type: object
                    :properties: {}
                  post:
                    :$ref: "#/components/schemas/post"
        :422:
          :description: Unprocessable Entity
          :content:
            :application/json:
              :schema:
                :type: object
                :properties:
                  issues:
                    :type: array
                    :items:
                      :$ref: "#/components/schemas/issue"
                :required:
                - issues
    delete:
      :operationId: postsDestroy
      :summary: Delete post
      :tags:
      - Posts
      :responses:
        :204:
          :description: No content
:components:
  :schemas:
    issue:
      :type: object
      :properties:
        code:
          :type: string
        detail:
          :type: string
        field:
          :type: string
        path:
          :type: array
          :items:
            :type: string
      :required:
      - code
      - detail
      - field
      - path
    nullableStringFilter:
      :type: object
      :properties:
        contains:
          :type: string
        endsWith:
          :type: string
        eq:
          :type: string
        in:
          :type: array
          :items:
            :type: string
        'null':
          :type: boolean
        startsWith:
          :type: string
    pagePagination:
      :type: object
      :properties:
        current:
          :type: integer
        items:
          :type: integer
        next:
          :type:
          - integer
          - 'null'
        prev:
          :type:
          - integer
          - 'null'
        total:
          :type: integer
      :required:
      - current
      - items
      - total
    post:
      :type: object
      :properties:
        body:
          :type: string
        createdAt:
          :type: string
        id:
          :type: integer
        status:
          :type: string
          :enum: &1
          - draft
          - published
          - archived
        title:
          :type: string
        updatedAt:
          :type: string
    postCreatePayload:
      :type: object
      :properties:
        body:
          :type:
          - string
          - 'null'
        status:
          :type:
          - string
          - 'null'
          :enum: *1
        title:
          :type: string
      :required:
      - title
    postFilter:
      :type: object
      :properties:
        _and:
          :type: array
          :items:
            :$ref: "#/components/schemas/postFilter"
        _not:
          :$ref: "#/components/schemas/postFilter"
        _or:
          :type: array
          :items:
            :$ref: "#/components/schemas/postFilter"
        status:
          :$ref: "#/components/schemas/postStatusFilter"
        title:
          :oneOf:
          - :type: string
          - :$ref: "#/components/schemas/stringFilter"
    postInclude:
      :type: object
      :properties: {}
    postPage:
      :type: object
      :properties:
        number:
          :type: integer
          :minimum: 1
        size:
          :type: integer
          :minimum: 1
          :maximum: 100
    postSort:
      :type: object
      :properties:
        createdAt: {}
        status: {}
    postStatusFilter:
      :oneOf:
      - :type: string
        :enum: *1
      - :type: object
        :properties:
          eq:
            :type: string
            :enum: *1
          in:
            :type: array
            :items:
              :type:
    postUpdatePayload:
      :type: object
      :properties:
        body:
          :type:
          - string
          - 'null'
        status:
          :type:
          - string
          - 'null'
          :enum: *1
        title:
          :type: string
      :required:
      - title
    stringFilter:
      :type: object
      :properties:
        contains:
          :type: string
        endsWith:
          :type: string
        eq:
          :type: string
        in:
          :type: array
          :items:
            :type: string
        startsWith:
          :type: string
