---
openapi: 3.1.0
info:
  title: "/eager_lion"
  version: 1.0.0
paths:
  "/invoices":
    get:
      operationId: invoices_index
      parameters:
      - in: query
        name: filter
        required: false
        schema:
          oneOf:
          - "$ref": "#/components/schemas/invoice_filter"
          - items:
              "$ref": "#/components/schemas/invoice_filter"
            type: array
      - in: query
        name: page
        required: false
        schema:
          "$ref": "#/components/schemas/invoice_page"
      - in: query
        name: sort
        required: false
        schema:
          oneOf:
          - "$ref": "#/components/schemas/invoice_sort"
          - items:
              "$ref": "#/components/schemas/invoice_sort"
            type: array
      responses:
        '200':
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/invoice_index_success_response_body"
          description: Successful response
    post:
      operationId: invoices_create
      requestBody:
        content:
          application/json:
            schema:
              properties:
                invoice:
                  "$ref": "#/components/schemas/invoice_create_payload"
              type: object
              required:
              - invoice
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/invoice_create_success_response_body"
          description: Successful response
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/error_response_body"
  "/invoices/{id}":
    get:
      operationId: invoices_show
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/invoice_show_success_response_body"
          description: Successful response
    patch:
      operationId: invoices_update
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              properties:
                invoice:
                  "$ref": "#/components/schemas/invoice_update_payload"
              type: object
              required:
              - invoice
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/invoice_update_success_response_body"
          description: Successful response
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/error_response_body"
    delete:
      operationId: invoices_destroy
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        '204':
          description: No content
  "/invoices/{id}/archive":
    patch:
      operationId: invoices_archive
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/invoice_archive_success_response_body"
          description: Successful response
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/error_response_body"
components:
  schemas:
    error_response_body:
      properties:
        issues:
          items:
            "$ref": "#/components/schemas/issue"
          type: array
        layer:
          enum:
          - http
          - contract
          - domain
          type: string
      type: object
      required:
      - issues
      - layer
    invoice:
      properties:
        created_at:
          type: string
          format: date-time
        customer:
          properties: {}
          type: object
        customer_id:
          type: string
        id:
          type: string
        issued_on:
          type:
          - string
          - 'null'
          format: date
        lines:
          items: {}
          type: array
        notes:
          type:
          - string
          - 'null'
        number:
          type: string
        status:
          type:
          - string
          - 'null'
        updated_at:
          type: string
          format: date-time
      type: object
      required:
      - created_at
      - customer
      - customer_id
      - id
      - issued_on
      - lines
      - notes
      - number
      - status
      - updated_at
    invoice_archive_success_response_body:
      properties:
        invoice:
          "$ref": "#/components/schemas/invoice"
        meta:
          properties: {}
          type: object
      type: object
      required:
      - invoice
    invoice_create_payload:
      properties:
        customer_id:
          type: string
        issued_on:
          type:
          - string
          - 'null'
          format: date
        lines:
          items: {}
          type: array
        notes:
          type:
          - string
          - 'null'
        number:
          type: string
      type: object
      required:
      - customer_id
      - number
    invoice_create_success_response_body:
      properties:
        invoice:
          "$ref": "#/components/schemas/invoice"
        meta:
          properties: {}
          type: object
      type: object
      required:
      - invoice
    invoice_filter:
      properties:
        _and:
          items:
            "$ref": "#/components/schemas/invoice_filter"
          type: array
        _not:
          "$ref": "#/components/schemas/invoice_filter"
        _or:
          items:
            "$ref": "#/components/schemas/invoice_filter"
          type: array
        number:
          oneOf:
          - type: string
          - "$ref": "#/components/schemas/string_filter"
        status:
          oneOf:
          - type: string
          - "$ref": "#/components/schemas/nullable_string_filter"
      type: object
    invoice_index_success_response_body:
      properties:
        invoices:
          items:
            "$ref": "#/components/schemas/invoice"
          type: array
        meta:
          properties: {}
          type: object
        pagination:
          "$ref": "#/components/schemas/offset_pagination"
      type: object
      required:
      - invoices
      - pagination
    invoice_page:
      properties:
        number:
          type: integer
          minimum: 1
        size:
          type: integer
          minimum: 1
          maximum: 100
      type: object
    invoice_show_success_response_body:
      properties:
        invoice:
          "$ref": "#/components/schemas/invoice"
        meta:
          properties: {}
          type: object
      type: object
      required:
      - invoice
    invoice_sort:
      properties:
        created_at:
          enum:
          - asc
          - desc
          type: string
        issued_on:
          enum:
          - asc
          - desc
          type: string
        status:
          enum:
          - asc
          - desc
          type: string
        updated_at:
          enum:
          - asc
          - desc
          type: string
      type: object
    invoice_update_payload:
      properties:
        customer_id:
          type: string
        issued_on:
          type:
          - string
          - 'null'
          format: date
        lines:
          items: {}
          type: array
        notes:
          type:
          - string
          - 'null'
        number:
          type: string
      type: object
    invoice_update_success_response_body:
      properties:
        invoice:
          "$ref": "#/components/schemas/invoice"
        meta:
          properties: {}
          type: object
      type: object
      required:
      - invoice
    issue:
      properties:
        code:
          type: string
        detail:
          type: string
        meta:
          properties: {}
          type: object
        path:
          items:
            type: string
          type: array
        pointer:
          type: string
      type: object
      required:
      - code
      - detail
      - meta
      - path
      - pointer
    nullable_string_filter:
      properties:
        contains:
          type: string
        ends_with:
          type: string
        eq:
          type: string
        in:
          items:
            type: string
          type: array
        'null':
          type: boolean
        starts_with:
          type: string
      type: object
    offset_pagination:
      properties:
        current:
          type: integer
        items:
          type: integer
        next:
          type:
          - integer
          - 'null'
        prev:
          type:
          - integer
          - 'null'
        total:
          type: integer
      type: object
      required:
      - current
      - items
      - total
    string_filter:
      properties:
        contains:
          type: string
        ends_with:
          type: string
        eq:
          type: string
        in:
          items:
            type: string
          type: array
        starts_with:
          type: string
      type: object
