---
:openapi: 3.1.0
:info:
  :title: "/clever_rabbit API"
  :version: 1.0.0
:paths:
  orders/:
    get:
      :operationId: ordersIndex
      :tags:
      - Orders
      :parameters:
      - :in: query
        :name: filter
        :required: false
        :schema:
          :oneOf:
          - :$ref: "#/components/schemas/orderFilter"
          - :type: array
            :items:
              :$ref: "#/components/schemas/orderFilter"
      - :in: query
        :name: include
        :required: false
        :schema:
          :$ref: "#/components/schemas/orderInclude"
      - :in: query
        :name: page
        :required: false
        :schema:
          :$ref: "#/components/schemas/orderPage"
      - :in: query
        :name: sort
        :required: false
        :schema:
          :oneOf:
          - :$ref: "#/components/schemas/orderSort"
          - :type: array
            :items:
              :$ref: "#/components/schemas/orderSort"
      :responses:
        :200:
          :description: Successful response
          :content:
            :application/json:
              :schema:
                :type: object
                :properties:
                  meta:
                    :type: object
                    :properties: {}
                  orders:
                    :type: array
                    :items:
                      :$ref: "#/components/schemas/order"
                  pagination:
                    :$ref: "#/components/schemas/pagePagination"
    post:
      :operationId: ordersCreate
      :tags:
      - Orders
      :parameters:
      - :in: query
        :name: include
        :required: false
        :schema:
          :$ref: "#/components/schemas/orderInclude"
      :requestBody:
        :required: true
        :content:
          :application/json:
            :schema:
              :type: object
              :properties:
                order:
                  :$ref: "#/components/schemas/orderCreatePayload"
              :required:
              - order
      :responses:
        :200:
          :description: Successful response
          :content:
            :application/json:
              :schema:
                :type: object
                :properties:
                  meta:
                    :type: object
                    :properties: {}
                  order:
                    :$ref: "#/components/schemas/order"
                :required:
                - order
        :422:
          :description: Unprocessable Entity
          :content:
            :application/json:
              :schema:
                :type: object
                :properties:
                  issues:
                    :type: array
                    :items:
                      :$ref: "#/components/schemas/issue"
  orders/:id:
    get:
      :operationId: ordersShow
      :tags:
      - Orders
      :parameters:
      - :in: query
        :name: include
        :required: false
        :schema:
          :$ref: "#/components/schemas/orderInclude"
      :responses:
        :200:
          :description: Successful response
          :content:
            :application/json:
              :schema:
                :type: object
                :properties:
                  meta:
                    :type: object
                    :properties: {}
                  order:
                    :$ref: "#/components/schemas/order"
                :required:
                - order
    patch:
      :operationId: ordersUpdate
      :tags:
      - Orders
      :parameters:
      - :in: query
        :name: include
        :required: false
        :schema:
          :$ref: "#/components/schemas/orderInclude"
      :requestBody:
        :required: true
        :content:
          :application/json:
            :schema:
              :type: object
              :properties:
                order:
                  :$ref: "#/components/schemas/orderUpdatePayload"
      :responses:
        :200:
          :description: Successful response
          :content:
            :application/json:
              :schema:
                :type: object
                :properties:
                  meta:
                    :type: object
                    :properties: {}
                  order:
                    :$ref: "#/components/schemas/order"
        :422:
          :description: Unprocessable Entity
          :content:
            :application/json:
              :schema:
                :type: object
                :properties:
                  issues:
                    :type: array
                    :items:
                      :$ref: "#/components/schemas/issue"
    delete:
      :operationId: ordersDestroy
      :tags:
      - Orders
      :responses:
        :204:
          :description: No content
:components:
  :schemas:
    issue:
      :type: object
      :properties:
        code:
          :type: string
        detail:
          :type: string
        field:
          :type: string
        path:
          :type: array
          :items:
            :type: string
      :required:
      - code
      - detail
      - field
      - path
    nullableStringFilter:
      :type: object
      :properties:
        contains:
          :type: string
        endsWith:
          :type: string
        eq:
          :type: string
        in:
          :type: array
          :items:
            :type: string
        'null':
          :type: boolean
        startsWith:
          :type: string
    order:
      :type: object
      :properties:
        createdAt:
          :type: string
        id: {}
        lineItems:
          :type: array
          :items:
            :type: string
        orderNumber:
          :type: string
        shippingAddress:
          :type: object
          :properties: {}
        status:
          :type: string
        total:
          :type: number
        updatedAt:
          :type: string
      :required:
      - lineItems
      - shippingAddress
    orderCreatePayload:
      :type: object
      :properties:
        lineItems:
          :type: array
          :items:
            :type: string
        orderNumber:
          :type: string
        shippingAddress:
          :type: object
          :properties: {}
      :required:
      - orderNumber
    orderFilter:
      :type: object
      :properties:
        _and:
          :type: array
          :items:
            :$ref: "#/components/schemas/orderFilter"
        _not:
          :$ref: "#/components/schemas/orderFilter"
        _or:
          :type: array
          :items:
            :$ref: "#/components/schemas/orderFilter"
        status:
          :oneOf:
          - :type: string
          - :$ref: "#/components/schemas/nullableStringFilter"
    orderInclude:
      :type: object
      :properties: {}
    orderPage:
      :type: object
      :properties:
        number:
          :type: integer
          :minimum: 1
        size:
          :type: integer
          :minimum: 1
          :maximum: 100
    orderSort:
      :type: object
      :properties:
        createdAt: {}
        status: {}
    orderUpdatePayload:
      :type: object
      :properties:
        lineItems:
          :type: array
          :items:
            :type: string
        orderNumber:
          :type: string
        shippingAddress:
          :type: object
          :properties: {}
      :required:
      - orderNumber
    pagePagination:
      :type: object
      :properties:
        current:
          :type: integer
        items:
          :type: integer
        next:
          :type:
          - integer
          - 'null'
        prev:
          :type:
          - integer
          - 'null'
        total:
          :type: integer
      :required:
      - current
      - items
      - total
    stringFilter:
      :type: object
      :properties:
        contains:
          :type: string
        endsWith:
          :type: string
        eq:
          :type: string
        in:
          :type: array
          :items:
            :type: string
        startsWith:
          :type: string
