---
openapi: 3.1.0
info:
  title: "/bold_falcon API"
  version: 1.0.0
paths:
  articles/:
    get:
      operationId: articlesIndex
      parameters:
      - in: query
        name: filter
        required: false
        schema:
          oneOf:
          - "$ref": "#/components/schemas/articleFilter"
          - type: array
            items:
              "$ref": "#/components/schemas/articleFilter"
      - in: query
        name: page
        required: false
        schema:
          "$ref": "#/components/schemas/articlePage"
      - in: query
        name: sort
        required: false
        schema:
          oneOf:
          - "$ref": "#/components/schemas/articleSort"
          - type: array
            items:
              "$ref": "#/components/schemas/articleSort"
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/articleIndexSuccessResponseBody"
    post:
      operationId: articlesCreate
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                article:
                  "$ref": "#/components/schemas/articleCreatePayload"
              required:
              - article
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/articleCreateSuccessResponseBody"
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/errorResponseBody"
  articles/{id}:
    get:
      operationId: articlesShow
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/articleShowSuccessResponseBody"
    patch:
      operationId: articlesUpdate
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                article:
                  "$ref": "#/components/schemas/articleUpdatePayload"
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/articleUpdateSuccessResponseBody"
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/errorResponseBody"
    delete:
      operationId: articlesDestroy
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '204':
          description: No content
components:
  schemas:
    article:
      type: object
      properties:
        body:
          type:
          - string
          - 'null'
        category:
          type:
          - object
          - 'null'
          properties: {}
        createdAt:
          type: string
          format: date-time
        id:
          type: string
        publishedOn:
          type:
          - string
          - 'null'
          format: date
        rating:
          type:
          - number
          - 'null'
        status:
          type:
          - string
          - 'null'
          enum:
          - draft
          - published
          - archived
        title:
          type: string
        updatedAt:
          type: string
          format: date-time
        viewCount:
          type:
          - integer
          - 'null'
      required:
      - body
      - createdAt
      - id
      - publishedOn
      - rating
      - status
      - title
      - updatedAt
      - viewCount
    articleCreatePayload:
      type: object
      properties:
        body:
          type:
          - string
          - 'null'
        publishedOn:
          type:
          - string
          - 'null'
          format: date
        status:
          type:
          - string
          - 'null'
          enum:
          - draft
          - published
          - archived
        title:
          type: string
      required:
      - title
    articleCreateSuccessResponseBody:
      type: object
      properties:
        article:
          "$ref": "#/components/schemas/article"
        meta:
          type: object
          properties: {}
      required:
      - article
    articleFilter:
      type: object
      properties:
        _and:
          type: array
          items:
            "$ref": "#/components/schemas/articleFilter"
        _not:
          "$ref": "#/components/schemas/articleFilter"
        _or:
          type: array
          items:
            "$ref": "#/components/schemas/articleFilter"
        publishedOn:
          oneOf:
          - type: string
            format: date
          - "$ref": "#/components/schemas/nullableDateFilter"
        rating:
          oneOf:
          - type: number
          - "$ref": "#/components/schemas/nullableDecimalFilter"
        status:
          "$ref": "#/components/schemas/articleStatusFilter"
        title:
          oneOf:
          - type: string
          - "$ref": "#/components/schemas/stringFilter"
        viewCount:
          oneOf:
          - type: integer
          - "$ref": "#/components/schemas/nullableIntegerFilter"
    articleIndexSuccessResponseBody:
      type: object
      properties:
        articles:
          type: array
          items:
            "$ref": "#/components/schemas/article"
        meta:
          type: object
          properties: {}
        pagination:
          "$ref": "#/components/schemas/offsetPagination"
      required:
      - articles
      - pagination
    articlePage:
      type: object
      properties:
        number:
          type: integer
          minimum: 1
        size:
          type: integer
          minimum: 1
          maximum: 100
    articleShowSuccessResponseBody:
      type: object
      properties:
        article:
          "$ref": "#/components/schemas/article"
        meta:
          type: object
          properties: {}
      required:
      - article
    articleSort:
      type: object
      properties:
        createdAt:
          type: string
          enum:
          - asc
          - desc
        publishedOn:
          type: string
          enum:
          - asc
          - desc
        rating:
          type: string
          enum:
          - asc
          - desc
        status:
          type: string
          enum:
          - asc
          - desc
        viewCount:
          type: string
          enum:
          - asc
          - desc
    articleStatusFilter:
      oneOf:
      - type: string
        enum:
        - draft
        - published
        - archived
      - type: object
        properties:
          eq:
            type: string
            enum:
            - draft
            - published
            - archived
          in:
            type: array
            items:
              type:
    articleUpdatePayload:
      type: object
      properties:
        body:
          type:
          - string
          - 'null'
        publishedOn:
          type:
          - string
          - 'null'
          format: date
        status:
          type:
          - string
          - 'null'
          enum:
          - draft
          - published
          - archived
        title:
          type: string
      required:
      - title
    articleUpdateSuccessResponseBody:
      type: object
      properties:
        article:
          "$ref": "#/components/schemas/article"
        meta:
          type: object
          properties: {}
      required:
      - article
    dateFilter:
      type: object
      properties:
        between:
          "$ref": "#/components/schemas/dateFilterBetween"
        eq:
          type: string
          format: date
        gt:
          type: string
          format: date
        gte:
          type: string
          format: date
        in:
          type: array
          items:
            type: string
        lt:
          type: string
          format: date
        lte:
          type: string
          format: date
    dateFilterBetween:
      type: object
      properties:
        from:
          type: string
          format: date
        to:
          type: string
          format: date
    decimalFilter:
      type: object
      properties:
        between:
          "$ref": "#/components/schemas/decimalFilterBetween"
        eq:
          type: number
        gt:
          type: number
        gte:
          type: number
        in:
          type: array
          items:
            type: number
        lt:
          type: number
        lte:
          type: number
    decimalFilterBetween:
      type: object
      properties:
        from:
          type: number
        to:
          type: number
    errorResponseBody:
      type: object
      properties:
        issues:
          type: array
          items:
            "$ref": "#/components/schemas/issue"
        layer:
          type: string
          enum:
          - http
          - contract
          - domain
      required:
      - issues
      - layer
    integerFilter:
      type: object
      properties:
        between:
          "$ref": "#/components/schemas/integerFilterBetween"
        eq:
          type: integer
        gt:
          type: integer
        gte:
          type: integer
        in:
          type: array
          items:
            type: integer
        lt:
          type: integer
        lte:
          type: integer
    integerFilterBetween:
      type: object
      properties:
        from:
          type: integer
        to:
          type: integer
    issue:
      type: object
      properties:
        code:
          type: string
        detail:
          type: string
        meta:
          type: object
          properties: {}
        path:
          type: array
          items:
            type: string
        pointer:
          type: string
      required:
      - code
      - detail
      - meta
      - path
      - pointer
    nullableDateFilter:
      type: object
      properties:
        between:
          "$ref": "#/components/schemas/dateFilterBetween"
        eq:
          type: string
          format: date
        gt:
          type: string
          format: date
        gte:
          type: string
          format: date
        in:
          type: array
          items:
            type: string
        lt:
          type: string
          format: date
        lte:
          type: string
          format: date
        'null':
          type: boolean
    nullableDecimalFilter:
      type: object
      properties:
        between:
          "$ref": "#/components/schemas/decimalFilterBetween"
        eq:
          type: number
        gt:
          type: number
        gte:
          type: number
        in:
          type: array
          items:
            type: number
        lt:
          type: number
        lte:
          type: number
        'null':
          type: boolean
    nullableIntegerFilter:
      type: object
      properties:
        between:
          "$ref": "#/components/schemas/integerFilterBetween"
        eq:
          type: integer
        gt:
          type: integer
        gte:
          type: integer
        in:
          type: array
          items:
            type: integer
        lt:
          type: integer
        lte:
          type: integer
        'null':
          type: boolean
    nullableStringFilter:
      type: object
      properties:
        contains:
          type: string
        endsWith:
          type: string
        eq:
          type: string
        in:
          type: array
          items:
            type: string
        'null':
          type: boolean
        startsWith:
          type: string
    offsetPagination:
      type: object
      properties:
        current:
          type: integer
        items:
          type: integer
        next:
          type:
          - integer
          - 'null'
        prev:
          type:
          - integer
          - 'null'
        total:
          type: integer
      required:
      - current
      - items
      - total
    stringFilter:
      type: object
      properties:
        contains:
          type: string
        endsWith:
          type: string
        eq:
          type: string
        in:
          type: array
          items:
            type: string
        startsWith:
          type: string
