---
openapi: 3.1.0
info:
  title: "/bold_falcon"
  version: 1.0.0
paths:
  "/articles":
    get:
      operationId: articlesIndex
      parameters:
      - in: query
        name: filter
        required: false
        schema:
          oneOf:
          - "$ref": "#/components/schemas/articleFilter"
          - items:
              "$ref": "#/components/schemas/articleFilter"
            type: array
      - in: query
        name: include
        required: false
        schema:
          "$ref": "#/components/schemas/articleInclude"
      - in: query
        name: page
        required: false
        schema:
          "$ref": "#/components/schemas/articlePage"
      - in: query
        name: sort
        required: false
        schema:
          oneOf:
          - "$ref": "#/components/schemas/articleSort"
          - items:
              "$ref": "#/components/schemas/articleSort"
            type: array
      responses:
        '200':
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/articleIndexSuccessResponseBody"
          description: Successful response
    post:
      operationId: articlesCreate
      parameters:
      - in: query
        name: include
        required: false
        schema:
          "$ref": "#/components/schemas/articleInclude"
      requestBody:
        content:
          application/json:
            schema:
              properties:
                article: {}
              type: object
              required:
              - article
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/articleCreateSuccessResponseBody"
          description: Successful response
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/errorResponseBody"
  "/articles/{id}":
    get:
      operationId: articlesShow
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      - in: query
        name: include
        required: false
        schema:
          "$ref": "#/components/schemas/articleInclude"
      responses:
        '200':
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/articleShowSuccessResponseBody"
          description: Successful response
    patch:
      operationId: articlesUpdate
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      - in: query
        name: include
        required: false
        schema:
          "$ref": "#/components/schemas/articleInclude"
      requestBody:
        content:
          application/json:
            schema:
              properties:
                article: {}
              type: object
              required:
              - article
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/articleUpdateSuccessResponseBody"
          description: Successful response
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/errorResponseBody"
    delete:
      operationId: articlesDestroy
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      - in: query
        name: include
        required: false
        schema:
          "$ref": "#/components/schemas/articleInclude"
      responses:
        '204':
          description: No content
components:
  schemas:
    article:
      properties:
        body:
          type:
          - string
          - 'null'
        category:
          oneOf:
          - "$ref": "#/components/schemas/category"
          - type: 'null'
        createdAt:
          type: string
          format: date-time
        id:
          type: string
        publishedOn:
          type:
          - string
          - 'null'
          format: date
        rating:
          type:
          - number
          - 'null'
        status:
          enum:
          - archived
          - draft
          - published
          type:
          - string
          - 'null'
        title:
          type: string
        updatedAt:
          type: string
          format: date-time
        viewCount:
          type:
          - integer
          - 'null'
      type: object
      required:
      - body
      - createdAt
      - id
      - publishedOn
      - rating
      - status
      - title
      - updatedAt
      - viewCount
    articleCreateSuccessResponseBody:
      properties:
        article:
          "$ref": "#/components/schemas/article"
        meta:
          properties: {}
          type: object
      type: object
      required:
      - article
    articleFilter:
      properties:
        AND:
          items:
            "$ref": "#/components/schemas/filter"
          type: array
        NOT:
          "$ref": "#/components/schemas/filter"
        OR:
          items:
            "$ref": "#/components/schemas/filter"
          type: array
        category: {}
        publishedOn:
          oneOf:
          - type: string
            format: date
          - "$ref": "#/components/schemas/nullableDateFilter"
        rating:
          oneOf:
          - type: number
          - "$ref": "#/components/schemas/nullableDecimalFilter"
        status:
          "$ref": "#/components/schemas/articleStatusFilter"
        title:
          oneOf:
          - type: string
          - "$ref": "#/components/schemas/stringFilter"
        viewCount:
          oneOf:
          - type: integer
          - "$ref": "#/components/schemas/nullableIntegerFilter"
      type: object
    articleInclude:
      properties:
        category:
          type: boolean
      type: object
    articleIndexSuccessResponseBody:
      properties:
        articles:
          items:
            "$ref": "#/components/schemas/article"
          type: array
        meta:
          properties: {}
          type: object
        pagination:
          "$ref": "#/components/schemas/offsetPagination"
      type: object
      required:
      - articles
      - pagination
    articlePage:
      properties:
        number:
          type: integer
          minimum: 1
        size:
          type: integer
          minimum: 1
          maximum: 100
      type: object
    articleShowSuccessResponseBody:
      properties:
        article:
          "$ref": "#/components/schemas/article"
        meta:
          properties: {}
          type: object
      type: object
      required:
      - article
    articleSort:
      properties:
        createdAt:
          enum:
          - asc
          - desc
          type: string
        publishedOn:
          enum:
          - asc
          - desc
          type: string
        rating:
          enum:
          - asc
          - desc
          type: string
        status:
          enum:
          - asc
          - desc
          type: string
        viewCount:
          enum:
          - asc
          - desc
          type: string
      type: object
    articleStatusFilter:
      oneOf:
      - enum:
        - archived
        - draft
        - published
        type: string
      - properties:
          eq:
            enum:
            - archived
            - draft
            - published
            type: string
          in:
            items:
              enum:
              - archived
              - draft
              - published
              type: string
            type: array
        type: object
        required:
        - eq
        - in
    articleUpdateSuccessResponseBody:
      properties:
        article:
          "$ref": "#/components/schemas/article"
        meta:
          properties: {}
          type: object
      type: object
      required:
      - article
    category:
      properties:
        id:
          type: string
        name:
          type: string
        slug:
          type: string
      type: object
      required:
      - id
      - name
      - slug
    dateFilterBetween:
      properties:
        from:
          type: string
          format: date
        to:
          type: string
          format: date
      type: object
    decimalFilterBetween:
      properties:
        from:
          type: number
        to:
          type: number
      type: object
    error:
      properties:
        issues:
          items:
            "$ref": "#/components/schemas/issue"
          type: array
        layer:
          enum:
          - http
          - contract
          - domain
          type: string
      type: object
      required:
      - issues
      - layer
    errorResponseBody:
      "$ref": "#/components/schemas/error"
    filter:
      properties:
        AND:
          items:
            "$ref": "#/components/schemas/filter"
          type: array
        NOT:
          "$ref": "#/components/schemas/filter"
        OR:
          items:
            "$ref": "#/components/schemas/filter"
          type: array
        name:
          oneOf:
          - type: string
          - "$ref": "#/components/schemas/stringFilter"
        slug:
          oneOf:
          - type: string
          - "$ref": "#/components/schemas/stringFilter"
      type: object
    integerFilterBetween:
      properties:
        from:
          type: integer
        to:
          type: integer
      type: object
    issue:
      properties:
        code:
          type: string
        detail:
          type: string
        meta:
          properties: {}
          type: object
        path:
          items:
            type: string
          type: array
        pointer:
          type: string
      type: object
      required:
      - code
      - detail
      - meta
      - path
      - pointer
    nullableDateFilter:
      properties:
        between:
          "$ref": "#/components/schemas/dateFilterBetween"
        eq:
          type: string
          format: date
        gt:
          type: string
          format: date
        gte:
          type: string
          format: date
        in:
          items:
            type: string
            format: date
          type: array
        lt:
          type: string
          format: date
        lte:
          type: string
          format: date
        'null':
          type: boolean
      type: object
    nullableDecimalFilter:
      properties:
        between:
          "$ref": "#/components/schemas/decimalFilterBetween"
        eq:
          type: number
        gt:
          type: number
        gte:
          type: number
        in:
          items:
            type: number
          type: array
        lt:
          type: number
        lte:
          type: number
        'null':
          type: boolean
      type: object
    nullableIntegerFilter:
      properties:
        between:
          "$ref": "#/components/schemas/integerFilterBetween"
        eq:
          type: integer
        gt:
          type: integer
        gte:
          type: integer
        in:
          items:
            type: integer
          type: array
        lt:
          type: integer
        lte:
          type: integer
        'null':
          type: boolean
      type: object
    offsetPagination:
      properties:
        current:
          type: integer
        items:
          type: integer
        next:
          type:
          - integer
          - 'null'
        prev:
          type:
          - integer
          - 'null'
        total:
          type: integer
      type: object
      required:
      - current
      - items
      - total
    stringFilter:
      properties:
        contains:
          type: string
        endsWith:
          type: string
        eq:
          type: string
        in:
          items:
            type: string
          type: array
        startsWith:
          type: string
      type: object
