---
openapi: 3.1.0
info:
  title: "/bold_falcon"
  version: 1.0.0
paths:
  "/articles":
    get:
      operationId: articles_index
      parameters:
      - in: query
        name: filter
        required: false
        schema:
          oneOf:
          - "$ref": "#/components/schemas/article_filter"
          - items:
              "$ref": "#/components/schemas/article_filter"
            type: array
      - in: query
        name: page
        required: false
        schema:
          "$ref": "#/components/schemas/article_page"
      - in: query
        name: sort
        required: false
        schema:
          oneOf:
          - "$ref": "#/components/schemas/article_sort"
          - items:
              "$ref": "#/components/schemas/article_sort"
            type: array
      responses:
        '200':
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/article_index_success_response_body"
          description: Successful response
    post:
      operationId: articles_create
      requestBody:
        content:
          application/json:
            schema:
              properties:
                article:
                  "$ref": "#/components/schemas/article_create_payload"
              type: object
              required:
              - article
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/article_create_success_response_body"
          description: Successful response
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/error_response_body"
  "/articles/{id}":
    get:
      operationId: articles_show
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/article_show_success_response_body"
          description: Successful response
    patch:
      operationId: articles_update
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              properties:
                article:
                  "$ref": "#/components/schemas/article_update_payload"
              type: object
              required:
              - article
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/article_update_success_response_body"
          description: Successful response
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/error_response_body"
    delete:
      operationId: articles_destroy
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        '204':
          description: No content
components:
  schemas:
    article:
      properties:
        body:
          type:
          - string
          - 'null'
        category:
          properties: {}
          type:
          - object
          - 'null'
        created_at:
          type: string
          format: date-time
        id:
          type: string
        published_on:
          type:
          - string
          - 'null'
          format: date
        rating:
          type:
          - number
          - 'null'
        status:
          enum:
          - archived
          - draft
          - published
          type:
          - string
          - 'null'
        title:
          type: string
        updated_at:
          type: string
          format: date-time
        view_count:
          type:
          - integer
          - 'null'
      type: object
      required:
      - body
      - created_at
      - id
      - published_on
      - rating
      - status
      - title
      - updated_at
      - view_count
    article_create_payload:
      properties:
        body:
          type:
          - string
          - 'null'
        published_on:
          type:
          - string
          - 'null'
          format: date
        status:
          enum:
          - archived
          - draft
          - published
          type:
          - string
          - 'null'
        title:
          type: string
      type: object
      required:
      - title
    article_create_success_response_body:
      properties:
        article:
          "$ref": "#/components/schemas/article"
        meta:
          properties: {}
          type: object
      type: object
      required:
      - article
    article_filter:
      properties:
        _and:
          items:
            "$ref": "#/components/schemas/article_filter"
          type: array
        _not:
          "$ref": "#/components/schemas/article_filter"
        _or:
          items:
            "$ref": "#/components/schemas/article_filter"
          type: array
        published_on:
          oneOf:
          - type: string
            format: date
          - "$ref": "#/components/schemas/nullable_date_filter"
        rating:
          oneOf:
          - type: number
          - "$ref": "#/components/schemas/nullable_decimal_filter"
        status:
          "$ref": "#/components/schemas/article_status_filter"
        title:
          oneOf:
          - type: string
          - "$ref": "#/components/schemas/string_filter"
        view_count:
          oneOf:
          - type: integer
          - "$ref": "#/components/schemas/nullable_integer_filter"
      type: object
    article_index_success_response_body:
      properties:
        articles:
          items:
            "$ref": "#/components/schemas/article"
          type: array
        meta:
          properties: {}
          type: object
        pagination:
          "$ref": "#/components/schemas/offset_pagination"
      type: object
      required:
      - articles
      - pagination
    article_page:
      properties:
        number:
          type: integer
          minimum: 1
        size:
          type: integer
          minimum: 1
          maximum: 100
      type: object
    article_show_success_response_body:
      properties:
        article:
          "$ref": "#/components/schemas/article"
        meta:
          properties: {}
          type: object
      type: object
      required:
      - article
    article_sort:
      properties:
        created_at:
          enum:
          - asc
          - desc
          type: string
        published_on:
          enum:
          - asc
          - desc
          type: string
        rating:
          enum:
          - asc
          - desc
          type: string
        status:
          enum:
          - asc
          - desc
          type: string
        view_count:
          enum:
          - asc
          - desc
          type: string
      type: object
    article_status_filter:
      oneOf:
      - enum:
        - archived
        - draft
        - published
        type: string
      - properties:
          eq:
            enum:
            - archived
            - draft
            - published
            type: string
          in:
            items:
              enum:
              - archived
              - draft
              - published
              type: string
            type: array
        type: object
        required:
        - eq
        - in
    article_update_payload:
      properties:
        body:
          type:
          - string
          - 'null'
        published_on:
          type:
          - string
          - 'null'
          format: date
        status:
          enum:
          - archived
          - draft
          - published
          type:
          - string
          - 'null'
        title:
          type: string
      type: object
    article_update_success_response_body:
      properties:
        article:
          "$ref": "#/components/schemas/article"
        meta:
          properties: {}
          type: object
      type: object
      required:
      - article
    date_filter_between:
      properties:
        from:
          type: string
          format: date
        to:
          type: string
          format: date
      type: object
    decimal_filter_between:
      properties:
        from:
          type: number
        to:
          type: number
      type: object
    error_response_body:
      properties:
        issues:
          items:
            "$ref": "#/components/schemas/issue"
          type: array
        layer:
          enum:
          - http
          - contract
          - domain
          type: string
      type: object
      required:
      - issues
      - layer
    integer_filter_between:
      properties:
        from:
          type: integer
        to:
          type: integer
      type: object
    issue:
      properties:
        code:
          type: string
        detail:
          type: string
        meta:
          properties: {}
          type: object
        path:
          items:
            type: string
          type: array
        pointer:
          type: string
      type: object
      required:
      - code
      - detail
      - meta
      - path
      - pointer
    nullable_date_filter:
      properties:
        between:
          "$ref": "#/components/schemas/date_filter_between"
        eq:
          type: string
          format: date
        gt:
          type: string
          format: date
        gte:
          type: string
          format: date
        in:
          items:
            type: string
            format: date
          type: array
        lt:
          type: string
          format: date
        lte:
          type: string
          format: date
        'null':
          type: boolean
      type: object
    nullable_decimal_filter:
      properties:
        between:
          "$ref": "#/components/schemas/decimal_filter_between"
        eq:
          type: number
        gt:
          type: number
        gte:
          type: number
        in:
          items:
            type: number
          type: array
        lt:
          type: number
        lte:
          type: number
        'null':
          type: boolean
      type: object
    nullable_integer_filter:
      properties:
        between:
          "$ref": "#/components/schemas/integer_filter_between"
        eq:
          type: integer
        gt:
          type: integer
        gte:
          type: integer
        in:
          items:
            type: integer
          type: array
        lt:
          type: integer
        lte:
          type: integer
        'null':
          type: boolean
      type: object
    offset_pagination:
      properties:
        current:
          type: integer
        items:
          type: integer
        next:
          type:
          - integer
          - 'null'
        prev:
          type:
          - integer
          - 'null'
        total:
          type: integer
      type: object
      required:
      - current
      - items
      - total
    string_filter:
      properties:
        contains:
          type: string
        ends_with:
          type: string
        eq:
          type: string
        in:
          items:
            type: string
          type: array
        starts_with:
          type: string
      type: object
