---
openapi: 3.1.0
info:
  title: "/bold_falcon API"
  version: 1.0.0
paths:
  articles/:
    get:
      operationId: articlesIndex
      tags:
      - Articles
      parameters:
      - in: query
        name: filter
        required: false
        schema:
          oneOf:
          - "$ref": "#/components/schemas/articleFilter"
          - type: array
            items:
              "$ref": "#/components/schemas/articleFilter"
      - in: query
        name: include
        required: false
        schema:
          "$ref": "#/components/schemas/articleInclude"
      - in: query
        name: page
        required: false
        schema:
          "$ref": "#/components/schemas/articlePage"
      - in: query
        name: sort
        required: false
        schema:
          oneOf:
          - "$ref": "#/components/schemas/articleSort"
          - type: array
            items:
              "$ref": "#/components/schemas/articleSort"
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  articles:
                    type: array
                    items:
                      "$ref": "#/components/schemas/article"
                  meta:
                    type: object
                    properties: {}
                  pagination:
                    "$ref": "#/components/schemas/offsetPagination"
    post:
      operationId: articlesCreate
      tags:
      - Articles
      parameters:
      - in: query
        name: include
        required: false
        schema:
          "$ref": "#/components/schemas/articleInclude"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                article:
                  "$ref": "#/components/schemas/articleCreatePayload"
              required:
              - article
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  article:
                    "$ref": "#/components/schemas/article"
                  meta:
                    type: object
                    properties: {}
                required:
                - article
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                type: object
                properties:
                  issues:
                    type: array
                    items:
                      "$ref": "#/components/schemas/issue"
  articles/:id:
    get:
      operationId: articlesShow
      tags:
      - Articles
      parameters:
      - in: query
        name: include
        required: false
        schema:
          "$ref": "#/components/schemas/articleInclude"
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  article:
                    "$ref": "#/components/schemas/article"
                  meta:
                    type: object
                    properties: {}
                required:
                - article
    patch:
      operationId: articlesUpdate
      tags:
      - Articles
      parameters:
      - in: query
        name: include
        required: false
        schema:
          "$ref": "#/components/schemas/articleInclude"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                article:
                  "$ref": "#/components/schemas/articleUpdatePayload"
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  article:
                    "$ref": "#/components/schemas/article"
                  meta:
                    type: object
                    properties: {}
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                type: object
                properties:
                  issues:
                    type: array
                    items:
                      "$ref": "#/components/schemas/issue"
    delete:
      operationId: articlesDestroy
      tags:
      - Articles
      responses:
        '204':
          description: No content
components:
  schemas:
    article:
      type: object
      properties:
        body:
          type: string
        category:
          type:
          - object
          - 'null'
          properties: {}
        createdAt:
          type: string
        id: {}
        publishedOn:
          type: string
        rating:
          type: number
        status:
          type: string
          enum:
          - draft
          - published
          - archived
        title:
          type: string
        updatedAt:
          type: string
        viewCount:
          type: integer
    articleCreatePayload:
      type: object
      properties:
        body:
          type:
          - string
          - 'null'
        publishedOn:
          type:
          - string
          - 'null'
        status:
          type:
          - string
          - 'null'
          enum:
          - draft
          - published
          - archived
        title:
          type: string
      required:
      - title
    articleFilter:
      type: object
      properties:
        _and:
          type: array
          items:
            "$ref": "#/components/schemas/articleFilter"
        _not:
          "$ref": "#/components/schemas/articleFilter"
        _or:
          type: array
          items:
            "$ref": "#/components/schemas/articleFilter"
        publishedOn:
          oneOf:
          - type: string
          - "$ref": "#/components/schemas/nullableDateFilter"
        rating:
          oneOf:
          - type: number
          - "$ref": "#/components/schemas/nullableDecimalFilter"
        status:
          "$ref": "#/components/schemas/articleStatusFilter"
        title:
          oneOf:
          - type: string
          - "$ref": "#/components/schemas/stringFilter"
        viewCount:
          oneOf:
          - type: integer
          - "$ref": "#/components/schemas/nullableIntegerFilter"
    articleInclude:
      type: object
      properties: {}
    articlePage:
      type: object
      properties:
        number:
          type: integer
          minimum: 1
        size:
          type: integer
          minimum: 1
          maximum: 100
    articleSort:
      type: object
      properties:
        createdAt:
          type: string
          enum:
          - asc
          - desc
        publishedOn:
          type: string
          enum:
          - asc
          - desc
        rating:
          type: string
          enum:
          - asc
          - desc
        status:
          type: string
          enum:
          - asc
          - desc
        viewCount:
          type: string
          enum:
          - asc
          - desc
    articleStatusFilter:
      oneOf:
      - type: string
        enum:
        - draft
        - published
        - archived
      - type: object
        properties:
          eq:
            type: string
            enum:
            - draft
            - published
            - archived
          in:
            type: array
            items:
              type:
    articleUpdatePayload:
      type: object
      properties:
        body:
          type:
          - string
          - 'null'
        publishedOn:
          type:
          - string
          - 'null'
        status:
          type:
          - string
          - 'null'
          enum:
          - draft
          - published
          - archived
        title:
          type: string
      required:
      - title
    dateFilter:
      type: object
      properties:
        between:
          "$ref": "#/components/schemas/dateFilterBetween"
        eq:
          type: string
        gt:
          type: string
        gte:
          type: string
        in:
          type: array
          items:
            type: string
        lt:
          type: string
        lte:
          type: string
    dateFilterBetween:
      type: object
      properties:
        from:
          type: string
        to:
          type: string
    decimalFilter:
      type: object
      properties:
        between:
          "$ref": "#/components/schemas/decimalFilterBetween"
        eq:
          type: number
        gt:
          type: number
        gte:
          type: number
        in:
          type: array
          items:
            type: number
        lt:
          type: number
        lte:
          type: number
    decimalFilterBetween:
      type: object
      properties:
        from:
          type: number
        to:
          type: number
    integerFilter:
      type: object
      properties:
        between:
          "$ref": "#/components/schemas/integerFilterBetween"
        eq:
          type: integer
        gt:
          type: integer
        gte:
          type: integer
        in:
          type: array
          items:
            type: integer
        lt:
          type: integer
        lte:
          type: integer
    integerFilterBetween:
      type: object
      properties:
        from:
          type: integer
        to:
          type: integer
    issue:
      type: object
      properties:
        code:
          type: string
        detail:
          type: string
        field:
          type: string
        path:
          type: array
          items:
            type: string
      required:
      - code
      - detail
      - field
      - path
    nullableDateFilter:
      type: object
      properties:
        between:
          "$ref": "#/components/schemas/dateFilterBetween"
        eq:
          type: string
        gt:
          type: string
        gte:
          type: string
        in:
          type: array
          items:
            type: string
        lt:
          type: string
        lte:
          type: string
        'null':
          type: boolean
    nullableDecimalFilter:
      type: object
      properties:
        between:
          "$ref": "#/components/schemas/decimalFilterBetween"
        eq:
          type: number
        gt:
          type: number
        gte:
          type: number
        in:
          type: array
          items:
            type: number
        lt:
          type: number
        lte:
          type: number
        'null':
          type: boolean
    nullableIntegerFilter:
      type: object
      properties:
        between:
          "$ref": "#/components/schemas/integerFilterBetween"
        eq:
          type: integer
        gt:
          type: integer
        gte:
          type: integer
        in:
          type: array
          items:
            type: integer
        lt:
          type: integer
        lte:
          type: integer
        'null':
          type: boolean
    nullableStringFilter:
      type: object
      properties:
        contains:
          type: string
        endsWith:
          type: string
        eq:
          type: string
        in:
          type: array
          items:
            type: string
        'null':
          type: boolean
        startsWith:
          type: string
    offsetPagination:
      type: object
      properties:
        current:
          type: integer
        items:
          type: integer
        next:
          type:
          - integer
          - 'null'
        prev:
          type:
          - integer
          - 'null'
        total:
          type: integer
      required:
      - current
      - items
      - total
    stringFilter:
      type: object
      properties:
        contains:
          type: string
        endsWith:
          type: string
        eq:
          type: string
        in:
          type: array
          items:
            type: string
        startsWith:
          type: string
