---
:openapi: 3.1.0
:info:
  :title: "/happy-zebra API"
  :version: 1.0.0
:paths: {}
:components:
  :schemas:
    status_filter:
      :oneOf:
      - {}
      - :type: object
        :properties:
          eq: {}
          in:
            :type: array
            :items:
              :type:
