---
:openapi: 3.1.0
:info:
  :title: "/lazy-cow API"
  :version: 1.0.0
:paths:
  posts/:
    get:
      :operationId: posts_index
      :tags:
      - Posts
      :responses:
        :204:
          :description: No content
    post:
      :operationId: posts_create
      :tags:
      - Posts
      :responses:
        :204:
          :description: No content
  posts/:id:
    get:
      :operationId: posts_show
      :tags:
      - Posts
      :responses:
        :204:
          :description: No content
    patch:
      :operationId: posts_update
      :tags:
      - Posts
      :responses:
        :204:
          :description: No content
    delete:
      :operationId: posts_destroy
      :tags:
      - Posts
      :responses:
        :204:
          :description: No content
:components:
  :schemas:
    issue:
      :type: object
      :properties:
        code:
          :type: string
        detail:
          :type: string
        field:
          :type: string
        path:
          :type: array
          :items:
            :type: string
      :required:
      - code
      - detail
      - field
      - path
