---
openapi: 3.1.0
info:
  title: "/lazy_cow"
  version: 1.0.0
paths:
  "/status/health":
    get:
      operationId: statusHealth
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  status:
                    type: string
                  timestamp:
                    type: string
                    format: date-time
                  version:
                    type: string
                type: object
                required:
                - status
                - timestamp
                - version
          description: Successful response
  "/status/stats":
    get:
      operationId: statusStats
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  postsCount:
                    type: integer
                  uptimeSeconds:
                    type: integer
                  usersCount:
                    type: integer
                type: object
                required:
                - postsCount
                - uptimeSeconds
                - usersCount
          description: Successful response
components:
  schemas: {}
